env:
  global:
    - GIT_DEPLOY_REPO=https://github.com/akbennett/akbennett.github.io.git
    - GIT_DEPLOY_DIR=docs # this is the default output dir of Hugo
    - GIT_DEPLOY_BRANCH=master # this is the target branch, replace by gh-pages for Project Pages
    - GIT_DEPLOY_USERNAME="Travis CI" # dummy name
    - GIT_DEPLOY_EMAIL=alan@akb.net # replace by your email
branches:
  only:
    - master # replace by master for Project Pages

install:
  - ls
script:
  - cd src
  - ../tools/hugo # generate!
after_success:
  - ls docs
  - echo "machine github.com" > ~/.netrc
  - echo "  login $GITHUB_TOKEN" >> ~/.netrc
  - bash ../tools/deploy.sh # run the deploy script
