languageCode = "en-us"
title = "Aerial"
baseurl = "https://akbennett.github.io/"
theme = "aerial"
publishDir = "docs"

[params]
  name = "Alan Bennett"
  about = "Engineering Leader&nbsp;&bull;&nbsp; Perspective &nbsp;&bull;&nbsp; Perseverance"
  copyright = "Alan Bennett"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/akbnet"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/alankbennett"

[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/alankbennett/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/akbennett"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://instagram.com/akbnet"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:alan-web@akb.net?Subject=Hello"
